src/RestClient.Website/ViewModels/ErrorViewModel.cs
namespace RestClient.Website.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/RestClient.Website/Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RestClient.Infra.Dtos;
using RestClient.Orm;

namespace RestClient.Website.Controllers
{
    public class ApiController : Controller
    {
        private DataProvider _provider;
        public ApiController(DataProvider provider)
        {
            _provider = provider;
        }
        public async Task<IActionResult> Index()
        {
            var apis = await _provider.ApiService.GetAll();
            return View(apis);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ApiDto api)
        {
            //validation
            await _provider.ApiService.Create(api);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var api = await _provider.ApiService.GetById(id);
            var endpoints = await _provider.EndpointService.GetAll();

            if (api == null)
            {
                return NotFound();
            }

            ViewData["Endpoints"] = new SelectList(endpoints, "Id", "Name");
            return View(api);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ApiDto api)
        {
            //validation
            await _provider.ApiService.Update(api.Id, api);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveEndpoint(Guid apiid, Guid endpointid)
        {
            await _provider.EndpointService.Delete(endpointid);
            return RedirectToAction(nameof(Edit), new { id = apiid });
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var api = await _provider.ApiService.GetById(id);
            if (api == null)
            {
                return NotFound();
            }
            
            return View(api);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var api = await _provider.ApiService.GetById(id);
            if (api == null)
            {
                return NotFound();
            }

            await _provider.ApiService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/RestClient.Website/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RestClient.Website.ViewModels;
using System.Diagnostics;

namespace RestClient.Website.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/RestClient.Website/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/RestClient.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestClient.Website.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Api" asp-action="Index">APIs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Endpoint" asp-action="Index">Endpoints</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataModel" asp-action="Index">DataModels</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Syter6</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>